### ISSUE TITLE
url that might be helpful

### ISSUE THREAD

**Issue by tanho63** [friscojosh/pfrscrapr#1]
https://www.pro-football-reference.com/short/inc/players_search_list.csv

**Comment by friscojosh** [comment]
Nice. Do you know if it's updated often?

**Comment by friscojosh** [comment]
Appears to be generated on the fly. I'll add a function that loads this. Sadly it's not a drop in replacement for the stuff I use this for, since I need positional data as well. But still very helpful. Thanks, Tan.

**Comment by friscojosh** [comment]
Will fix

**Comment by friscojosh** [comment]
Will fix
